### ISSUE TITLE
Strapi fails to start with TypeError

### ISSUE THREAD

**Issue by jonathanffon** [Roslovets-Inc/strapi-plugin-ckeditor5#16]
Hello,
      strapi compiled successfully after executing `strapi build`, but strapi didn't start with `strapi develop`.
```
➜  strapi yarn strapi develop
yarn run v1.22.4
$ strapi develop
[2021-04-24T11:04:16.412Z] debug ⛔️ Server wasn't able to start properly.
[2021-04-24T11:04:16.414Z] error TypeError: Cannot read property 'routes' of undefined
    at /home/jonathan/Public/cms/strapi/node_modules/strapi-plugin-users-permissions/middlewares/users-permissions/index.js:35:35
    at /home/jonathan/Public/cms/strapi/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/jonathan/Public/cms/strapi/node_modules/lodash/lodash.js:3032:24)
    at /home/jonathan/Public/cms/strapi/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/home/jonathan/Public/cms/strapi/node_modules/lodash/lodash.js:9410:14)
    at Object.initialize (/home/jonathan/Public/cms/strapi/node_modules/strapi-plugin-users-permissions/middlewares/users-permissions/index.js:34:11)
    at /home/jonathan/Public/cms/strapi/node_modules/strapi/lib/middlewares/index.js:43:28
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` 

How can I solve this problem. I am using node v14.14.0 && strapi v3.0.0-beta.19.3

**Comment by jonathanffon** [comment]
Updated to strapi v3.6.0. Problem solved.
