### ISSUE TITLE
Cannot convert undefined or null to object when moving dynamic component

### ISSUE THREAD

**Issue by joeyyax** [Roslovets-Inc/strapi-plugin-ckeditor5#30]
I have several dynamic zones configured within Strapi that contain CK editor. Everything works great, until you try to move one of those zones up or down. At that point the following error is thrown:
```
Cannot convert undefined or null to object
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at cs.set (http://localhost:1337/admin/main.756de919.chunk.js:1:6876335)
    at cs.<anonymous> (http://localhost:1337/admin/main.756de919.chunk.js:1:6672788)
    at cs.fire (http://localhost:1337/admin/main.756de919.chunk.js:1:6664247)
    at cs.<computed> [as set] (http://localhost:1337/admin/main.756de919.chunk.js:1:6672839)
    at kw.setData (http://localhost:1337/admin/main.756de919.chunk.js:1:6942234)
    at Nt.shouldComponentUpdate (http://localhost:1337/admin/main.756de919.chunk.js:1:6323295)
    at bi (http://localhost:1337/admin/main.756de919.chunk.js:1:4238055)
    at Na (http://localhost:1337/admin/main.756de919.chunk.js:1:4257548)
    at gs (http://localhost:1337/admin/main.756de919.chunk.js:1:4294368)
```

This behavior persists with and without a custom config defined in `/extensions/ckeditor5/admin/src/config/ckeditor.js`.

**Comment by TimLanzi** [comment]
I am experiencing this as well

**Comment by hymair** [comment]
Just ran into this as well.

**Comment by igormariuta** [comment]
+1

**Comment by Bligoubloups** [comment]
Hi, I've the same issue, I can prevent the crash by adding some text in the editor before moving the zone.
Maybe it can help to fix.
